version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalGitprojectTest_NewProject
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
- name: TPPWithVar
  version: "1.0"
  gitServerName: GH_SK
  gitUrl: https://github.com/Lakshitha-Ramesh-IBM
  gitUsername: santhu736852
  gitBranch: main
- name: Package3
  version: "1.0"
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
