version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalGitprojectTest_NewProject
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
- name: TPPWithVar
  version: "1.0"
  gitServerName: GH_SK
  gitUrl: https://github.com/Lakshitha-Ramesh-IBM
  gitUsername: santhu736852
  gitBranch: main
- name: Package2
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.externalgitprojecttest_new.integrations:NonDAF
  packages:
  - name: ExternalGitprojectTest_NewProject
    version: "1.0"
  - name: Package1
    version: "1.0"
  - name: TPPWithVar
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.868
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
